### ISSUE TITLE
suggestion: make any dyeable block clickable

### ISSUE THREAD

**Issue by RCXcrafter** [QVBA/RightClickDye#1]
It would be cool if you could make it so that any dyeable block can be clicked with a dye to dye it.
Here's how you could do that:
When a block is clicked with a dye, check if the block is used in a crafting recipe with that dye and nothing else
If the output is a block, replace the block with the output and consume the item.
It's okay if you can't do this but I think it would be really cool since it will automatically support any other mod's blocks.

Maybe you could also enable this for other items, such as pistons and slimeballs.

**Comment by QVBA** [comment]
I'm cautious about writing something to dye blocks based on if they can be crafted with dye and nothing else. The issue is that currently my code gets the dye that the user clicked with, converts it into Minecraft's colour code by hijacking the sheep dye code (since Dyes use damage values, rather than colour codes), then finds the wool with that colour code. 

I'm worried that if I tried to support all mods with dyeable blocks, that the greater majority of them simply won't use the same colours as Minecraft wool blocks do. There are probably a lot more mods which will crash than it will work for. So, if I wanted to support all blocks without causing a crash, I'd have to override the block itself and replace it with my own re-textured version, most likely breaking any blocks which provide functionality (such as BC pipes), and causing more problems than the fix in question would solve.

I don't mind adding support for specific mods however, assuming I can get permission from the mod authors, and they use Minecraft color codes and/or provide a way to convert between their own colours and Minecraft's. If there are any mods you specifically want support for, add them as an issue and preface the title with 'IMPROVEMENT:' and I'll see what I can do.

Thanks for your interest in my mod :)

**Comment by RCXcrafter** [comment]
I didn't mean that you should make every single block dyeable. What I meant was that you could 
right click on a block with an item to do a crafting recipe without opening a gui, as long as the crafting recipe only involves one block and one item.

**Comment by QVBA** [comment]
@RCXcrafter My reply was based on the idea that the crafting recipe only involved one block and one item. There are way too many edge cases for this to feasibly possible. It would be much easier to write each mod seperately.
